### ISSUE TITLE
zero current implementations of Turtle/TriG/N-Triples/N-Quads functionality are spec compliant, because none can "ensure that malignant strings may not be used to mislead the reader" — there's just no way to do so!

### ISSUE THREAD

**Issue by TallTed** [w3c/rdf-concepts#11]
_Originally posted by @TallTed in https://github.com/w3c/rdf-concepts/pull/7#discussion_r1092328636_

```
    Application rendering strings retrieved from untrusted RDF documents must ensure
    that malignant strings may not be used to mislead the reader.
```
>>> @[TallTed](https://github.com/TallTed) [18 hours ago](https://github.com/w3c/rdf-concepts/pull/7#discussion_r1091284122)
>>>
>>> I don't believe this requirement can be satisfied by any applications available today, if ever.
>>>
>>> As things stand, humans must take care to load varyingly trustworthy RDF into appropriately partitioned data stores (typically, using named graphs), and to execute queries across "all data in the store" only when recognizing that results may include malicious, erroneous, or otherwise undesirable statements (whether triples or quads).
>>>
>>> Such undesirable results are not the responsibility of any software in the stack.
>>
>> @[gkellogg](https://github.com/gkellogg) [18 hours ago](https://github.com/w3c/rdf-concepts/pull/7#discussion_r1091294960)
>>
>> It's taken right out of the [Turtle IANA Considerations section](https://www.w3.org/TR/turtle/#sec-mediaReg)
>>
>> Turtle can express data which is presented to the user, for example, RDF Schema labels. Application rendering strings retrieved from untrusted Turtle documents must ensure that malignant strings may not be used to mislead the reader. The security considerations in the media type registration for XML ([[RFC3023](https://www.w3.org/TR/turtle/#bib-RFC3023)] section 10) provide additional guidance around the expression of arbitrary data and markup.
>>
>> I didn't want to try to tread new ground here, but ReSpec demands that specs have such a section, and this seemed to apply generally to RDF serializations. I also don't want to revisit the IANA registrations of Turtle/TriG/N-Triples/N-Quads which already have such considerations, and it would be inconsistent to say something different.
>
> @[TallTed](https://github.com/TallTed) [now](https://github.com/w3c/rdf-concepts/pull/7#discussion_r1092328636)
>
> Wow. As I understand things, that means that zero current implementations of Turtle/TriG/N-Triples/N-Quads functionality are spec compliant, because none can "ensure that malignant strings may not be used to mislead the reader" — there's just no way to do so!

**Comment by afs** [comment]
I don't think it says that. 

It is in a section "security consideration". It is something applications (not parsers) should be aware of.  The word "compliance" is not mentioned.

https://github.com/w3c/rdf-concepts/pull/7#discussion_r1092345472

**Comment by TallTed** [comment]
@afs — Do you consider "parsers" to be disjoint from "applications"? I consider "parsers" to be a subtype of "applications"...

This section may well be informative, not normative, in all cases; that's great, it means that existing apps are no less compliant by not "[ensuring] that malignant strings may not be used to mislead the reader".

Still, that sentence is quite likely to mislead many readers. It definitely over-promises the capabilities of all "Application rendering strings retrieved from untrusted RDF documents", and I strongly feel that it should be changed, in all locations.

**Comment by afs** [comment]
If you have improvements, great.

The title of this issue introduces the word "compliant" - not the spec text.

Parsers are not string-rendering applications and often library code. They do not know the end-intent. What is safe in one situation is not safe in another.

"considerations" are important advice such as the Turtle text and in context such as
"Applications interpreting data expressed in Turtle should address the security issues of ..."
I find it clear. 

s/Application rendering strings/Applications rendering strings/ would be better and I consider it editorial.

**Comment by gkellogg** [comment]
Actually, I think #11 will do; I'll update the section with an issue reference.

**Comment by TallTed** [comment]
> I don't understand who "the reader" is.

As I see it, "the reader" (which I took from the original phrasing) is the agent — whether social agent, software agent, or otherwise — that consumes the RDF documents and/or any of the strings (which I read as "literals", whether typed or untyped, though this might well include URLs/URIs/IRIs) they contain.

(If you disagree with my interpretation, or even if you agree, you're pretty damn knowledgable in this arena, so I'd expect you to understand the intended meaning of a worthwhile warning without any trouble. Some rephrasing, whether mine above or some further revision, seems called for.)

> Framed as widely as your suggestion, it might be better in RDF Concepts.

I don't immediately disagree. Whether it should *only* be in RDF Concepts is another question to be considered.

**Comment by gkellogg** [comment]
On the subject of general security considerations, and of particular interest for N-Triples and N-Quads canonicalization, is the ability for RDF Literals to include un-escaped control characters, which may obfuscate the content in presentation. 

See https://github.com/w3c/rdf-n-quads/issues/16

**Comment by TallTed** [comment]
My concern is with the phrase `must ensure that malignant strings may not be used to mislead the reader`.

Malignant strings may have many origins, many reasons for being presented to the reader; and there's virtually no computational way to ensure the innocuousness of any given string being presented to the reader.

This stricture is entirely unachievable, and it should be removed from all specs that currently contain it.
