### ISSUE TITLE
Presentation of the definition of Triple Terms

### ISSUE THREAD

**Issue by afs** [w3c/rdf-concepts#110]
(Refers to RDF Concepts as of 2024-11-01)

There is no section for the definition of "Triple Term" - this stands out in the TOC for section [3. RDF Graphs](https://www.w3.org/TR/rdf12-concepts/#section-rdf-graph).

[3. RDF Graphs](https://www.w3.org/TR/rdf12-concepts/#section-rdf-graph)
* [3.1 Triples](https://www.w3.org/TR/rdf12-concepts/#section-triples)
* [3.2 IRIs](https://www.w3.org/TR/rdf12-concepts/#section-IRIs)
* [3.3 Literals](https://www.w3.org/TR/rdf12-concepts/#section-Graph-Literal)
  * [3.3.1 Initial Text Direction](https://www.w3.org/TR/rdf12-concepts/#section-text-direction)
* [3.4 Blank Nodes](https://www.w3.org/TR/rdf12-concepts/#section-blank-nodes)
* [3.5 Replacing Blank Nodes with IRIs](https://www.w3.org/TR/rdf12-concepts/#section-skolemization)
* [3.6 Graph Comparison](https://www.w3.org/TR/rdf12-concepts/#graph-isomorphism)

3 subsections for RDF terms, no subsection for "Triple Term".

The definition of "triple term" is within section 3.1 ("Triples").

There is section [1.3 Triple Terms](https://www.w3.org/TR/rdf12-concepts/#section-triple-terms) which discusses triple terms, reifying triples and reification.

Suggestion:
* Rename 1.3 as "Triple Terms and Reification"
* Create a new subsection "Triple Terms" in section 3 with the material from "A triple term is a 3-tuple that is defined recursively as follows:" to the end of the three notes.

The new "Triple terms" subsection could go after "Blank Nodes" before "Replacing Blank Nodes", to agree with the order in [IRIs](https://www.w3.org/TR/rdf12-concepts/#dfn-iri), [literals](https://www.w3.org/TR/rdf12-concepts/#dfn-literal), [blank nodes](https://www.w3.org/TR/rdf12-concepts/#dfn-blank-node), and [triple terms](https://www.w3.org/TR/rdf12-concepts/#dfn-triple-term) are collectively known as RDF terms.

For consistency, maybe move the discussion "Initial Text Direction" (non-normative section ) to after the normative, defining sections for triples and the 4 RDF terms. "Replacing Blank Nodes with IRIs" is already a separate section. If keeping to the earlier term order style, "Initial Text Direction", then "Replacing Blank Nodes with IRIs".

**Comment by afs** [comment]
While working on this issue, I notices that the use of h2/h3 header levels is inconsistent. Teh indentation is consistent. It does not affect the rendered HTML.

<details><summary>Output of grep for <code>&lt;h.\&gt;</code> with indent</summary>

```
  <h2>Introduction</h2>
    <h3>Graph-based Data Model</h3>
    <h3>Resources and Statements</h3>
    <h3>Triple Terms and Reification</h3>
    <h3>The Referent of an IRI</h3>
    <h3>RDF Vocabularies and Namespace IRIs</h3>
    <h2>RDF and Change over Time</h2>
    <h3>Working with Multiple RDF Graphs</h3>
    <h3>Equivalence, Entailment and Inconsistency</h3>
    <h2>RDF Documents and Syntaxes</h2>
    <h2>Strings in RDF</h2>
  <h2>RDF Graphs</h2>
    <h3>Triples</h3>
    <h3>IRIs</h3>
    <h2>Literals</h2>
    <h2>Blank Nodes</h2>
    <h3>Triple Terms</h3>
    <h3>Initial Text Direction</h3>
    <h3>Replacing Blank Nodes with IRIs</h3>
    <h3>Graph Comparison</h3>
  <h2>RDF Datasets</h2>
    <h3>RDF Dataset Comparison</h3>
    <h3>Content Negotiation of RDF Datasets</h3>
      <h3>Dataset as a Set of Quads</h3>
  <h2>Datatypes</h2>
    <h3>The XML Schema Built-in Datatypes</h3>
    <h3>Datatype IRIs</h3>
  <h2>Fragment Identifiers</h2>
  <h2>Generalized RDF Triples, Graphs, and Datasets</h2>
  <h2>Additional Datatypes</h2>
    <h3>The <code>rdf:HTML</code> Datatype</h3>
    <h3>The <code>rdf:XMLLiteral</code> Datatype</h3>
    <h3>The <code>rdf:JSON</code> Datatype</h3>
  <h2>Privacy Considerations</h2>
  <h2>Security Considerations</h2>
  <h2>Internationalization Considerations</h2>
  <h2>IRI Grammar</h2>
  <h2>Acknowledgments</h2>
    <h3>Acknowledgments for RDF 1.0</h3>
    <h3>Acknowledgments for RDF 1.1</h3>
    <h3>Acknowledgments for RDF 1.2</h3>
  <h2>Changes between RDF 1.1 and RDF 1.2</h2>
```

</details>

**Comment by afs** [comment]
The sections "The Referent of an IRI" and "RDF Vocabularies and Namespace IRIs" seem more generally important. The section order `would` be:

* 1.2 Resources and Statements
* 1.3 The Referent of an IRI
* 1.4 RDF Vocabularies and Namespace IRIs
* 1.5 Triple Terms and Reification
* 1.6 RDF and Change over Time

**Comment by gkellogg** [comment]
> While working on this issue, I notices that the use of h2/h3 header levels is inconsistent. Teh indentation is consistent. It does not affect the rendered HTML.
> 
> Output of grep for `<h.\>` with indent

While they should be consistent, ReSpec ignores which particular form is used, IIRC.

**Comment by TallTed** [comment]
> While they should be consistent, ReSpec ignores which particular form is used, IIRC.

Yes, as long as the `<section>` tags are properly nested and closed, ReSpec will change the `<H#>` tags as the `<section>` tags indicate.
