### ISSUE TITLE
Quoted Triples

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-concepts#23]
The [RDF-star CG Report](https://w3c.github.io/rdf-star/cg-spec/2021-12-17.html#concepts) describes the core concepts `RDF-star graph`, `RDF-star dataset`, and `RDF-star triple`. Additionally, it defines `quoted triple`, `asserted triple`, and `constituent terms`.

This issue is for either using these definitions in RDF 1.2 Concepts, or updating the definitions of core components in RDF 1.2 to include the notion of a triple as an RDF term so that a triple is inherently recursively defined.

**Comment by hartig** [comment]
> [...] or updating the definitions of core components in RDF 1.2 to include the notion of a triple as an RDF term so that a triple is inherently recursively defined.

I would say that this is not possible because it would require definitions that have a circular dependency on one another. Instead, the notion of an RDF triple (assuming an RDF 1.2 version that incorporates RDF-star) has to defined in a recursive way as done in the CG report.
