### ISSUE TITLE
Terminology for graph/dataset without triple terms.

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-concepts#34]
Related to https://github.com/w3c/rdf-star-wg/issues/19, https://github.com/w3c/rdf-star-wg/issues/23, and https://github.com/w3c/rdf-star-wg/issues/33, this issue considers the need to define terminology for triples either containing an embedded triple, or not, as well as graphs and datasets which may or may not contain such triples.

Terms discussed previously for this are:

* `complex triple` (also `nested triple`) – a triple in which either the subject or object is a `quoted triple`
* `plain triple` (also `simple triple` or `flat triple` – the complement of `complex triple` in which neither subject nor objet is a `quoted triple`.
* `complex graph` (also `nested graph`) – a graph containing at least one `complex triple`
* `plain graph` (also `simple graph` or `flat graph`) – the complement of `complex graph`.
* `complex dataset` (also `nested dataset `) – a dataset containing at least one `complex graph `
* `plain dataset ` (also `simple graph` or `flat dataset `) – the complement of `complex dataset `.

**Comment by afs** [comment]
What about w3c/rdf-star-wg#19 and w3c/rdf-star-wg#23?

Spreading discussions across multiple places is unhelpful.

One possibility not noted is that we have RDF 1.2 and a profile of RDF 1.2. 

That is all that is needed.  A dataset or graph conforms to the profile of RDF 1.2. ie. the set of RDF terms of the graph/datasets has no quoted triples. "graph" and "graph with no quoted triples".

There is no need to make duplicate terminology.

**Comment by afs** [comment]
Changed title from "term" to "terminology" - "term" as in "RDF term" is something else.

**Comment by gkellogg** [comment]
Such concepts already exist with the definition of **Full conformance** and **Classic conformance*.

We could consider terms such as "Fully conforming RDF Graph/Dataset" and "Classically conforming RDF Graph/Dataset".
