### ISSUE TITLE
Add Note about xsd:float and xsd:double Limitations

### ISSUE THREAD

**Issue by jmkeil** [w3c/rdf-concepts#43]
What about adding a remark in section [The XML Schema Built-in Datatypes](https://w3c.github.io/rdf-concepts/spec/#xsd-datatypes) to increase the awareness of the limitations of the values spaces of `xsd:float` and` xsd:double` (see [EasierRDF#82](https://github.com/w3c/EasierRDF/issues/82#issuecomment-1436738861) and https://doi.org/10.1007/978-3-031-06981-9_10)? Something like:

* add in the last column of the table
  >(but excluding many decimal numbers like `0.1`)

  or
  >(but not all decimal numbers)
* somewhere after the table add a NOTE box like:
  > The Lexical-to-value mapping of `xsd:float` and` xsd:double` performs a rounding of the lexical value to the nearest value representable in [IEEE 754-2008](http://ieeexplore.ieee.org/servlet/opac?punumber=4610933) binary floating point representation of the according precission. Therefore, many decimal numbers are not exactly represented by `xsd:float` and` xsd:double`. For example,
  > `ex:a ex:p "0.1"^^xsd:float.`
  > actually represents / [D-entails](https://w3c.github.io/rdf-semantics/spec/#datatype_entailment_patterns)
  > `ex:a ex:p "0.100000001490116119384765625"^^xsd:float.`
  > Only `xsd:decimal` can exactly represent arbitrarry decimal numbers.

**Comment by hartig** [comment]
@jmkeil thanks for the suggestion! I have created PR #44 with this change (using slightly different wording).
