### ISSUE TITLE
When do I need to use Quoted Triples as the subject instead of a regular URI?

### ISSUE THREAD

**Issue by chenkuncloud** [w3c/rdf-concepts#64]
## Question 1:
What can [Quoted Triples](https://www.w3.org/TR/rdf12-concepts/#section-quoted-triples) be used for? When do I need to use `Quoted Triples` as the subject instead of a regular URI? Can you give a specific example?

## Question 2:
`Quoted Triples` is a new feature of [RDF 1.2](https://www.w3.org/TR/rdf12-concepts/). When did it come out? I saw that it is already supported in [Apache Jena](https://jena.apache.org/documentation/rdf-star/).

**Comment by afs** [comment]
Jena supports quoted triples as defined by the RDF-Star Community Group (CG). The CG preceded the Working Group. The CG published https://w3c.github.io/rdf-star/cg-spec/2021-12-17.html which is input to th working group.

The Working Group is in-progress, and documents are working drafts, subject to change.

Jena will track the work of the Working Group outputs.

**Comment by chenkuncloud** [comment]
Thanks.

I understand that these documents are working drafts, not the final form.

But what is the purpose of `Quoted Triples`, and in what situations will semantic web developers use `Quoted Triples` as the subject instead of the regular `URI`?

**Comment by afs** [comment]
There is an introduction and motivation section in the CG report and there are examples in several sections.

Quoted triples allow the data to refer to the triple - for example, who has stated the triple? who believes the fact described by a triple? Quoted triples are the building blocks for this.

The CG report also discusses the relation to RDF Reification.

**Comment by chenkuncloud** [comment]
Thanks!
