### ISSUE TITLE
Pointers to use case drivers for "RDF Source"

### ISSUE THREAD

**Issue by ericstephan** [w3c/rdf-concepts#71]
Section 1.6 ( https://www.w3.org/TR/rdf12-concepts/#change-over-time )  refers to the concept of RDF source, a container of graphs that is "persistent, yet mutable over time".  Are there previous public discussion threads on this topic that you can share?

**Comment by TallTed** [comment]
Something like this topic has arisen in MANY spaces over the ~20 years since RDF came into common use. The gist is that, much like a single URI may persistently resolve to a single conceptual page (like a company's home page), the content of that page may change over time (changing the list of recent press releases, other news mentions, new product announcements, etc.), a single URI may conceptually resolve to an RDF source that describes a company, but the specific contents of that description (e.g., CEO name, last year's profits, etc.) may change over time.

Perhaps that answers the questions that brought you to ask about such discussion threads?

**Comment by ericstephan** [comment]
Thanks Ted for the response, I started doing a literature research on temporal RDF, and found many articles.   Just for grins because you mentioned the extensive history I asked a generative AI app what it could scoop up and it gave a pretty extensive list of use cases.  Because of the extensive history, it would be really nice to bring this out in potentially a separate note that section 1.6 could reference. I'd be happy to draft something for consideration.

**Comment by TallTed** [comment]
@ericstephan -- 

Are you able to join the [RDF-star Working Group](https://www.w3.org/groups/wg/rdf-star/participants/)? That would let us most easily accept such a draft for massaging into, and publication as, a WG Note. 

Failing that, are you able to join the [RDF-DEV Community Group](https://www.w3.org/groups/cg/rdf-dev/participants/)? That would let us most easily accept such a draft for massaging into, and publication as, a CG Report.

Such a WG Note or CG Report can then be referenced from this WG's output documents.

(One cautionary note — Generative AI apps are often based on outdated data corpus; for instance, the corpus used by ChatGPT4 was [stopped in 2021](https://www.enterpriseappstoday.com/stats/chatgpt-4-statistics.html#:~:text=%2326.-,ChatGPT%20can%20only%20gather%20data%20prior%20to%20the%20year%202021,the%20latest%20updates%20to%20readers.), and lacks any more-recent data. Thus, it may be worth verifying the current status of whatever is listed by your chosen generative AI app.)

**Comment by ericstephan** [comment]
***@***.**** I am checking into joining the community group (its a lower bar
to hurdle than getting my organization to join).  Agreed about the
generative AI caution, it was interesting feedback from years past.

**Comment by pfps** [comment]
@ericstephan Is there anything more that you think the working group should do here?  Your comment isn't exactly in areas that the working group is supposed to be working but the working group would like to check whether you want us to do something.

For now, I'm tagging this issue as something that should be considered resolved but that is only tentative and I'll remove the tag if there is something that the working group should do.
