### ISSUE TITLE
Confusing example of distinguishability of IRIs and literals

### ISSUE THREAD

**Issue by jyasskin** [w3c/rdf-concepts#72]
https://www.w3.org/TR/rdf12-concepts/#section-triples has

> [IRIs](https://www.w3.org/TR/rdf12-concepts/#dfn-iri), [literals](https://www.w3.org/TR/rdf12-concepts/#dfn-literal), [blank nodes](https://www.w3.org/TR/rdf12-concepts/#dfn-blank-node), and [quoted triples](https://www.w3.org/TR/rdf12-concepts/#dfn-quoted-triple) are distinct and distinguishable. For example, `http://example.org/` as a string literal is equal to neither `http://example.org/` as an IRI ...

When I first read this, I looked up the definition of [IRI](https://www.w3.org/TR/rdf12-concepts/#dfn-iri), found "An IRI ... is a [string](https://www.w3.org/TR/rdf12-concepts/#dfn-rdf-string)" and thought this was a discriminated union where someone had forgotten to tag the components. In fact, I should have looked up the definition of [literal](https://www.w3.org/TR/rdf12-concepts/#dfn-literal) and discovered that "http://example.org/ as a string literal" meant the pair ("http://example.org", "xsd:string"), which is clearly different from the IRI/string "http://example.org/".

I'd suggest updating this example with an indication that literals include their types, so something like

> ... For example, `http://example.org/^^xsd:string` as a literal is equal to neither `http://example.org/` as an IRI ...

**Comment by hartig** [comment]
@jyasskin see PR #73 -- or directly in the following preview of that PR: https://pr-preview.s3.amazonaws.com/w3c/rdf-concepts/pull/73.html#section-triples
