### ISSUE TITLE
Change section that (currently) introduces 'quoted triples'

### ISSUE THREAD

**Issue by hartig** [w3c/rdf-concepts#81]
The current draft of RDF 1.2 Concepts contains a section that describes what quoted triples are ([Section 1.3](https://w3c.github.io/rdf-concepts/spec/#section-quoted-triples)). As the WG has moved away from the notion of quoted triples, this section needs to be changed such that it does not mention quoted triples anymore but, instead, describes whatever new concept the WG settles on.

**Comment by gkellogg** [comment]
Both Turtle and Trig PRs (w3c/rdf-turtle#51 and w3c/rdf-trig#33) reference a definition for `reification` in RDF Concepts (`#dfn-reification`). Presumably, this would go into a PR which satisfies this issue. Alternatively, the definition could go in RDF Semantics, but as it seems to be a core concept in RDF 1.2 I think it probably belongs in RDF Concepts.
