### ISSUE TITLE
rdf:JSON value space too liberal

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-concepts#87]
The value space contains elements like the list that is its only member. There is nothing wrong with this, but I don't believe that such values are part of JSON and they certainly cause problems in serialization. If these values are not wanted a datatypes expert should be consulted to provide the best wording for excluding them.

My wording change would be to add "the smallest set containing" to the definition.

**Comment by gkellogg** [comment]
Can you elaborate on this, perhaps with some JSON examples that illustrate the problem.

Regarding "value space contains elements like the list that is its only member", if you're saying that a value can be a list with no members (e.g., `[]`), then this is valid JSON that is intended to be representable using this datatype.

> My wording change would be to add "the smallest set containing" to the definition.

Where do you think such a statement should go?

**Comment by pfps** [comment]
In most programming languages data structures can be self-referential.  So the list that has itself as its only member is fine in these languages, e.g., LISP.  The list that has itself as its only member is not the empty list.  Nor is it the list that has one member that is a list that has one member that is a list that has one member that is a list etc.  But all three of these are in the definition.  

To remove these non-well-founded elements a common practice in some areas is to say something like "The [value space](https://w3c.github.io/rdf-concepts/spec/#dfn-value-space) is the smallest set containing  [strings](https://w3c.github.io/rdf-concepts/spec/#dfn-rdf-string), ...."     There are many other ways of saying the same thing, and I do not know if this wording is currently acceptable in programming language or data structure specifications.

**Comment by gkellogg** [comment]
The notion of self-including is similar to that we describe for Triple Terms:

> The definition of [triple term](https://www.w3.org/TR/rdf12-concepts/#dfn-triple-term) is recursive. That is, a [triple term](https://www.w3.org/TR/rdf12-concepts/#dfn-triple-term) can itself have an [object](https://www.w3.org/TR/rdf12-concepts/#dfn-object) component which is another [triple term](https://www.w3.org/TR/rdf12-concepts/#dfn-triple-term). However, by this definition, cycles of [triple terms](https://www.w3.org/TR/rdf12-concepts/#dfn-triple-term) cannot be created.

I think the concern you're expressing about lists having themselves as a member is similar. In both cases, the grammars do not provide a way to create lists that have themselves as entries, either directly or recursively. Same for maps.

**Comment by pfps** [comment]
Except that triple terms are grammar elements and thus can be said to be created.   rdf:JSON values just exist.
